USE MINTCLASSICS;
-- RETRIVING DATA FROM ALL TABLES
SELECT * FROM customers;
select * FROM EMPLOYEES;
SELECT * FROM OFFICES;
SELECT * FROM ORDERDETAILS;
SELECT * FROM ORDERS ;
SELECT * FROM PAYMENTS; 
SELECT * FROM PRODUCTLINES;
SELECT * FROM PRODUCTS;
SELECT * FROM WAREHOUSES;
