USE MINTCLASSICS;
-- TOTAL PRODUCT
SELECT SUM(QUANTITYINSTOCK) AS TOTAL_PRODUCTS FROM PRODUCTS; -- WE HAVE 555131 PRODUCTS
--  PRODUCT WITH HIGH INVENTORY AND LESS SALES     .......    2002 SUZUKI XERO AND 1995 HONDA CIVIC SHOULD BE REMOVED
select P.PRODUCTNAME, (SUM(O.QUANTITYORDERED)) AS PRODUCT_SOLD , P.QUANTITYINSTOCK , P.QUANTITYINSTOCK-(SUM(O.QUANTITYORDERED)) AS PRODUCTS_REMAINING   FROM ORDERDETAILS O , PRODUCTS P WHERE P.PRODUCTCODE=O.PRODUCTCODE GROUP BY P.PRODUCTNAME , P.QUANTITYINSTOCK ORDER BY PRODUCTS_REMAINING DESC ;
-- AVERAGE , MAX , MIN SALES      ......     AVERAGE SALES OF 35.219 PRODUCTS , AMD MAX AND MIN PRODUCT ORDERS ARE 97 AND 6 RESPECTIVELY
SELECT  avg(QUANTITYORDERED) AS AVERAGESALES , MAX(QUANTITYORDERED) AS MAX_ORDERED, MIN(QUANTITYORDERED) AS MIN_ORDERED FROM ORDERDETAILS; -- AVG SALES




