-- FIND TOTAL NUMBER OF PRODUCTS IN EACH WAREHOUSE
USE MINTCLASSICS;
-- FINDING WAREHOUSE WISE CAPACITY , FILLED QUANTITY AND SPACE LEFT 
SELECT   W.WAREHOUSECODE, COUNT(PRODUCTCODE) AS PRODUCT_COUNT , W.WAREHOUSEPCTCAP , W.WAREHOUSEPCTCAP-COUNT(PRODUCTCODE) AS UNITS_LEFT  FROM PRODUCTS P , WAREHOUSES W WHERE P.WAREHOUSECODE=W.WAREHOUSECODE GROUP BY WAREHOUSECODE ; 
-- CONCLUSION
-- PRODUCTS IN WAREHOUSE C AND D CAN BE SHIFTED TO WAREHOUSE A 